apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: giteavol
  name: giteavol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
status: {}
